### ISSUE TITLE
Could not import not-return-value macro

### ISSUE THREAD

**Issue by mzp** [ajhc/ajhc#34]
We could not call non-return-value macro via FFI.

This is example:
#### foo.h

```
// this is ok
#define ONE() 1
// this is ng
#define NOP() do {} while(0)
```
#### Main.hs

```
module Main where
import System.IO
foreign import capi "foo.h ONE" one :: IO Int
foreign import capi "foo.h NOP" nop :: IO ()

main = do n <- one
                 nop -- this line cause compile error
                 putStrLn $ show n
```
#### How to build

```
$ ajhc "--optc=-I." -fffi Main.hs 
(snip)
/tmp/jhc_12833/main_code.c: In function ‘ftheMain’:
/tmp/jhc_12833/main_code.c:128:15: error: expected expression before ‘do’
(snip)
```
#### Generated file

```
   (snip)
   uint32_t v115160440 = ((uint32_t)ONE());
   (void)NOP();   // <- this statement cause the error
   uint16_t v100000 = (((int32_t)0) > ((int32_t)v115160440));
   (snip)
```

**Comment by mzp** [comment]
To fix this is not so diffucult(Like this: https://github.com/mzp/ajhc/commit/a8461bb87b4de2b28c6cfe3fd1099e306b772dae), it could pass all tests.

But we should discuss following things:
- Is this right way to call non-return-value macro?
- Remove (void) cast from function call is always correct?

**Comment by master-q** [comment]
Another answer is primitive "const.C_CONSTANT" catch IO type.
But current Ajhc does not support it...

**Comment by master-q** [comment]
Totally, I agree your code mzp@a8461bb.
Could you pull request or commit directly? > mzp

**Comment by mzp** [comment]
I commited. thx!

**Comment by master-q** [comment]
Thank's for your great work!
