### ISSUE TITLE
Purely a quick question

### ISSUE THREAD

**Issue by chrisdone** [ajhc/ajhc#4]
What is JHC/AJHC's runtime system written in? Is it in C or ASM or what? And does (A)JHC compile _to_ C? I'm curious about whether Emscripten could compile the results of JHC programs.

**Comment by master-q** [comment]
Jhc's rutime is written in pure C language. No ASM.
Jhc compile Haskell code to pure C language.

I think you like the below figure.

http://metasepi.masterq.net/draw/2012-12-22-jhc_compile.png

**Comment by chrisdone** [comment]
Cool! So I could try [Emscripten](https://github.com/kripken/emscripten/wiki) with AJHC. =)

Thanks!
