### ISSUE TITLE
build fail. lack of dependency of cpphs

### ISSUE THREAD

**Issue by osiire** [ajhc/ajhc#42]
I tried to install ajhc(0.8.0.8) on debian linux box,  but it was failed.

$ cabal install ajhc
...
ajhc 0.8.0.8 (a1265f031e6b75f9346ec23ca7caec0b5ced82bc)
Creating library from description file: "lib/jhc/jhc.yaml"
Reading: "lib/jhc/jhc.yaml"
Finding Dependencies...
Using Ho Cache: '/home/osiire/.ajhc/cache'
Data.Ratio              [lib/jhc/Data/Ratio.hs]
Jhc.Basics              [lib/jhc/Jhc/Basics.hs]
Jhc.Int                 [lib/jhc/Jhc/Int.hs]
Jhc.Type.Word           [lib/jhc/Jhc/Type/Word.hs]
Jhc.Type.Basic          [lib/jhc/Jhc/Type/Basic.hs]
Jhc.Class.Real          [lib/jhc/Jhc/Class/Real.hs]
Jhc.Class.Num           [lib/jhc/Jhc/Class/Num.hs]
Jhc.Class.Ord           [lib/jhc/Jhc/Class/Ord.hs]
Jhc.Show                [lib/jhc/Jhc/Show.hs]
Writing stuff:/tmp/jhc_5716/prelude.m4
Jhc.Enum                [lib/jhc/Jhc/Enum.hs]
Jhc.Inst.PrimEnum       [lib/jhc/Jhc/Inst/PrimEnum.hs]
Jhc.Float               [lib/jhc/Jhc/Float.hs]
Jhc.Inst.Num            [lib/jhc/Jhc/Inst/Num.hs]
Jhc.Inst.Enum           [lib/jhc/Jhc/Inst/Enum.hs]
Jhc.IO                  [lib/jhc/Jhc/IO.hs]
'cpphs -I. -Ilib/jhc -D__JHC__=800 -D__JHC_VERSION__=0.8.0.8 lib/jhc/Jhc/Options.hs' exited abnormally (ExitFailure 127)
make: **\* [jhc-1.0.hl] エラー 1
cabal: Error: some packages failed to install:
ajhc-0.8.0.8 failed during the building phase. The exception was:
ExitFailure 2

Maybe "cpphs" was needed in build-depends entry(ajhc.cabal.in).

**Comment by master-q** [comment]
Fixed at https://github.com/ajhc/ajhc/commit/0f4d9a92a622cf1ea4ddae3b433ce802dbeeeb86 .
Thank's for your report !
