### ISSUE TITLE
Only derive-2.5.12 error "Parse error: Last statement in a do-block must be an expression". It's not duplicated with derive-2.5.11.

### ISSUE THREAD

**Issue by master-q** [ajhc/ajhc#44]
Track upstream ticket. https://code.google.com/p/ndmitchell/issues/detail?id=622&colspec=ID%20Status%20Proj%20Summary%20Priority%20Stars

**Comment by ndmitchell** [comment]
Thanks for the report @master-q . I suspect it is indeed the haskell-src-exts-1.14 upgrade. I probably won't be able to take a detailed look until the weekend, and given my Windows only setup at the moment, replicating the error might be tricky. In the linked bug you get the error:

```
derive: fromParseResult: Parse failed at [/tmp/ghc24176_0/ghc24176_1.hspp] (355:5): Parse error: Last statement in a do-block must be an expression
```

Is it possible for you to find and attach the `/tmp/ghc24176_0/ghc24176_1.hspp` file (it may be different each time round) as that would make it much easier to debug in isolation.

**Comment by master-q** [comment]
I applied following patch to derive-2.5.12

``` .diff
diff --git a/Derive/Main.hs b/Derive/Main.hs
index f0216db..dd1552a 100644
--- a/Derive/Main.hs
+++ b/Derive/Main.hs
@@ -14,6 +14,7 @@ import System.Directory
 deriveMain :: [Derivation] -> IO ()
 deriveMain derivations = do
     (flags,files) <- getFlags
+    print files
     if Test `elem` flags then
         test
      else if Generate `elem` flags then
```

And try compile latest Ajhc.

```
$ autoreconf -i; ./configure; make install
--snip--
Building ajhc-0.8.0.9...
Preprocessing library ajhc-0.8.0.9...
shift/reduce conflicts:  60
reduce/reduce conflicts: 74
["src/C/FFI.hs","src/C/FFI.hs","/tmp/ghc25395_0/ghc25395_0.hspp"]
["src/C/FromGrin2.hs","src/C/FromGrin2.hs","/tmp/ghc25395_0/ghc25395_1.hspp"]
derive: fromParseResult: Parse failed at [/tmp/ghc25395_0/ghc25395_1.hspp] (355:5): Parse error: Last statement in a do-block must be an expression
```

Then, I think errored hspp file is based on src/C/FromGrin2.hs.
https://github.com/ajhc/ajhc/blob/arafura/src/C/FromGrin2.hs#L355

**Comment by master-q** [comment]
I think it's confused with the indent... But is it wrong???

**Comment by ndmitchell** [comment]
It is confused with the indent. To parse the indent it needs some extension pragma that GHC applies by default. I've just made derive use that pragma as well, and that test case failed with derive-2.5.12 but now works with derive-2.5.13. Can you update derive and try again?

**Comment by master-q** [comment]
Green! I think derive-2.5.13 does not have the problem.
Thank's for your speed to fix it.
