### ISSUE TITLE
Out c code depends on gcc undefiend behavior

### ISSUE THREAD

**Issue by mzp** [ajhc/ajhc#52]
This issues might be related with #28.

I recieved two reports from @kikairoya(C++ hacker).
- A identifier containing `$` and `__` is invalid. (https://twitter.com/kikairoya/status/389309169917890560)
- void function could not return value as long as it is void function. (see code snippet 1)(https://twitter.com/kikairoya/status/389312415935901696)
### code snippet 1

``` c
static void A_STD
ftheMain(gc_t gc,arena_t arena)
{
 (snip)
 return jhc_utf8_putchar((int)10);
}
```

**Comment by master-q** [comment]
> A identifier containing $ and __ is invalid.

I think it's not bad, because jhc's symbol should not overlap C language's.

**Comment by master-q** [comment]
> void function could not return value as long as it is void function. (see code snippet 1)

I wrote a patch to fix it. https://github.com/ajhc/ajhc/pull/58
Could you review it? @mzp

**Comment by mzp** [comment]
I agreed with your opinion about a symbol cotaining `$` and `__`.

We will re-open this issues when encounter a compiler complaining these identifier.
